media_path: ./testdata
temp_path: ""
original_handling: keep
workers: 3
ffmpeg_path: ffmpeg
ffprobe_path: ffprobe
queue_file: config/queue.json
pushover_user_key: ""
pushover_app_token: ""
notify_on_complete: false
quality_hevc: 0
quality_av1: 0
schedule_enabled: false
schedule_start_hour: 22
schedule_end_hour: 6
log_level: info
